### ISSUE TITLE
show taken pieces 

### ISSUE THREAD

**Issue by frankiebee** [Happy0/ssb-chess#27]
would be supper nice if you could see the pieces you've taken and visa versa

**Comment by Happy0** [comment]
Indeed :)

Some chess services show only the difference in material. For example, if you're winning material wise by a bishop and a pawn, then a bishop + pawn is shown.

Did you say you wanted to attempt to add this at some point? I'll hold off from doing it unless I run out of other things to do (which is unlikely for a while :P)

**Comment by Happy0** [comment]
Done :D (in version 1.9.2)
