### ISSUE TITLE
this is a thing?

### ISSUE THREAD

**Issue by frankiebee** [Happy0/ssb-chess#39]
is this how you want it too look?
<img width="1438" alt="screen shot 2017-10-22 at 2 00 36 pm" src="https://user-images.githubusercontent.com/11225267/31866242-8c8903ba-b731-11e7-989e-c9a7c4a2ce8f.png">

**Comment by Happy0** [comment]
yes, that is how I want it to look :3.  closing as no bug.

(Just kidding, it's been fixed.)
