### ISSUE TITLE
Error when castling

### ISSUE THREAD

**Issue by bencevans** [Happy0/ssb-chess#59]
```
Cannot read property 'role' of undefined
TypeError: Cannot read property 'role' of undefined
    at isPromotionMove (/home/bencevans/Code/patchbay/node_modules/ssb-chess/ui/game/gameView.js:52:37)
    at after (/home/bencevans/Code/patchbay/node_modules/ssb-chess/ui/game/gameView.js:127:17)
    at /home/bencevans/Code/patchbay/node_modules/chessground/board.js:11:43
```

This is happening on the most recent version of patchbay master https://github.com/ssbc/patchbay/commit/c6d3917a9dbbaf49b201e4e3964cb2e77346e9d3

Steps to reproduce:

1. King and Rook in a position to castle
2. Click King ... Green dots appear
4. Click Rook... :boom: ... error page shows with above stacktrace

**Comment by Happy0** [comment]
Interesting. When I castle I usually click the square next to the rook (the
king's destination square.)

Your way should work though! I'll give it a try and see if I get the error
:).

Thanks!
.

**Comment by Happy0** [comment]
Good steps to reproduce :D. I think that is the source of the issue.

I think I have a fix for it. I've invited you to a new game and I'll try it out once we get to a position where I can castle @bencevans :D.
