### ISSUE TITLE
Fixing security problems

### ISSUE THREAD

**Issue by arj03** [Happy0/ssb-chess#68]
Hi

I was going through the tons of security bugs in patchbay and in that process fixed ssb-backlinks. Could you update it to latest version? Thanks :)

**Comment by Happy0** [comment]
@arj03 done, published a new version, and added a commit to patchbay master to use that version of ssb-chess. Can you check that I haven't overlooked something? =]

**Comment by arj03** [comment]
Works. Thanks! No high security :-)
