### ISSUE TITLE
NPM Release?

### ISSUE THREAD

**Issue by christianbundy** [Happy0/ssb-chess#69]
Hey @Happy0!

I'm running into https://github.com/ssbc/patchbay/issues/211 and it looks like it may be resolved by `ssb-chess@2.2.9`. It looks like  the release appears on GitHub, but I don't see it on NPM. Would you mind publishing the latest version to NPM if you have some time?

Thanks! Let me know if there's anything I can help with.

**Comment by Happy0** [comment]
Sorry @christianbundy  , I totally missed this. I've released 2.2.9 now and bumped patchbay to use `ssb-chess@2.2.9` on master.

Please let me know if that fixes the issue.

**Comment by christianbundy** [comment]
Looks great, thank you!
